{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "newrelic.common.naming.fullname" . }}-role
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "newrelic.common.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "newrelic.common.naming.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "newrelic.common.serviceAccount.name" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
